### ISSUE TITLE
Creating a basic SPNEGO Authentication

### ISSUE THREAD

**Issue by macdrai** [pythongssapi/python-gssapi#101]
Hello,

Sorry to post an issue for this but the doc is quite hard to grasp.
I would like to create a basic SPNEGO auth with Kerberos but it seems that I can't verify the users Negociate token.
I have created my service principal called AUTH/server.domain.com@domain.com and I have my principal user@domain.com.

Here's my try, I have already kinit on the server:
```
   client_token = [...]
   servercreds = gssapi.Credentials(usage='accept')
   print(servercreds.name) # Return correctly AUTH/server.domain.com@domain.com
   server_ctx = gssapi.SecurityContext(creds=servercreds, usage='accept')
   [...]
   out_token = server_ctx.step(client_token)
```
Python is giving me this error: 
```
Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639056): Wrong principal in request
```
Does that mean that my  AUTH/server.domain.com@domain.com principal is incorrectly configured ?
I can kinit with both my user and service principal on the machine.
I'm using python3 and MIT Kerberos 5
Thank you very much.

**Comment by DirectXMan12** [comment]
The code you have provided should work.  Just in case, I've provided an example below.  I suspect that the issue is your principal name.  Are you using this for HTTP SPENGO (i.e. [RFC 4559](https://tools.ietf.org/html/rfc4559))? If so, notice that RFC 4559 specifies:

>  When the Kerberos Version 5 GSSAPI mechanism [RFC4121] is being used, the HTTP server will be using a principal name of the form of "HTTP/hostname".

So you should be using `HTTP/server.domain.com@DOMAIN.COM`, instead of `AUTH/server.domain.com@domain.com`.  Additionally, it's probably easier to use a keytab for your server instead of kinit-ing for it (extract the keytab to a secure place, and then use the  `KRB5_KTNAME` environment variable to make KRB5 use that keytab).

#### Example ####

Basic SPNEGO auth flow: https://gist.github.com/DirectXMan12/3f36666c26f0df4e024f

The code there is designed to be run under [gssapi-console](http://github.com/pythongssapi/gssapi-console), but that's only to properly set up the environment (i.e. the `REALM.xyz` parts at the beginning).  If you have an existing environment, you should be able to comment out the `REALM.xyz` lines and have that code work fine.

**Comment by simo5** [comment]
@macdrai can you show the client code too ?

**Comment by macdrai** [comment]
Hello, thank you for your responses.
I'm actually using cURL with NSS for the client Auth.
```
curl 7.19.7 libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

I've changed the principal to HTTP/server.domain.com@domain.com and I do not have the error anymore.
I had errors about the keytab so I added my keytab to the KRB5_KTNAME env variable.
It seems that I still can't auth users and I think it is because of the name_type=gssapi.NameType.hostbased_service value.
When using this, I have this error:
```
`Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100004): 
```
Without this value, the error is
```
Unspecified GSS failure.  Minor code may provide more information, Minor (2529639142): Key version number for principal in key table is incorrect
```
I guess I must have the value correctly set to hostbased_service to make it work.
I modified your example and I have the same minor error value, 100004. There's no info in the logs of my KDC server. If I remove the name_type, the server starts correctly, receive the user token. and correctly parse it. 
Do you have any clues about this error 100004 ? Thank you very much.

**Comment by simo5** [comment]
You have the wrong keytab or your rotated it but did not flush the client ccache and the client is still using the keys of the old keytab.

**Comment by macdrai** [comment]
Hello,
Thanks to both of you I found my error. I am using a proxy between the SPNEGO end point and the users. It seems the token is generated using part of the domain name. I'm fiddling with the headers to make it work, but right now the negotiation is definitely working when I'm directly querying the right server. Thank you for your generous help once again. You can close the ticket.
Is there a simple mechanism to optain the principal once the user correcly pass its token to the server and the security context is complete ?

**Comment by DirectXMan12** [comment]
Glad to help.  Let us know if there's anything we can do to make the documentation clearer (did you look over the [tutorial](http://pythonhosted.org/gssapi/basic-tutorial.html) at all?  Was it helpful or confusing in any way?)
