### ISSUE TITLE
GSI authentication

### ISSUE THREAD

**Issue by muccix** [pythongssapi/python-gssapi#110]
I'm attempting to use your library for a python client which has to authenticate using GSI to an iRODS server.
I saw your tutorial about Kerberos authentication.
Is any example with GSI available?
Many thanks!

**Comment by DirectXMan12** [comment]
Sorry, I'm not familiar with GSI, can you provide some more details?

**Comment by frozencemetery** [comment]
(For what it's worth, using another mechanism is going to be very similar; GSSAPI is an abstraction layer, so as long as there is a GSI mechanism for GSSAPI, the calls are pretty much the same.)

**Comment by muccix** [comment]
I'm trying to create a python client which should do something similar to what it is done in C++ [here](https://github.com/irods/irods_auth_plugin_gsi/blob/master/gsi/libgsi.cpp).
The call to the gss functions, such as gss_init_sec_context or gss_import_name should be doable with the python-GSSAPI, right?

**Comment by DirectXMan12** [comment]
> The call to the gss functions, such as gss_init_sec_context or gss_import_name should be doable with the python-GSSAPI, right?

Yep, those have direct low-level counterparts in python-gssapi (e.g. http://pythonhosted.org/gssapi/gssapi.raw.html#gssapi.raw.sec_contexts.init_sec_context), but you'll probably want to use the high-level variants (http://pythonhosted.org/gssapi/gssapi.html#module-gssapi.sec_contexts).  The tutorial that shows how to work with Kerberos should be generally applicable to GSI as well -- the C++ file you linked seems to be mostly doing the same thing: acquiring credentials, resolving names, and handling security contexts.

**Comment by muccix** [comment]
Ok, thanks for the info.
I'm trying to acquire credentials with 
`creds = gssapi.Credentials.acquire(name=None, lifetime=0, mechs=None, usage='accept')`. 
AFAIU this should trigger the Globus GSI library to search for a valid certificate in the filesystem, is this correct?

I'm getting the following error:

 File "/usr/local/lib/python2.7/dist-packages/gssapi/creds.py", line 137, in acquire
    mechs, usage)
  File "gssapi/raw/creds.pyx", line 158, in gssapi.raw.creds.acquire_cred (gssapi/raw/creds.c:1731)
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639093): Keytab FILE:/etc/krb5.keytab is nonexistent or empty

Should I specify a different MechType not to use Kerberos (something like "GSS_C_NULL_OID_SET")?

**Comment by simo5** [comment]
@muccix the default GSSAPI mechanism is krb5. That said in theory GSSAPI should try all enabled mechanism.
To make sue the GSI mechanism works try to pass in the GSI mechanism OID and see what happens.
I trust you enabled the GSI mechanism in /etc/gss/mech or /etc/gss/mech.d/gsi.conf ?

**Comment by muccix** [comment]
Maybe I was following the wrong path: unfortunately it's hard to find GSI documentation and my only reference for the moment is the C++ class I posted previously.
Since I'm developing the client side, I guess I can avoid acquiring credentials and I can jump to the initialization of the SecurityContext.
What is not clear to me is what I should pass as name to the SecurityContext. 
The `client_ctx.step()` return an error sayng: "Configuration file does not specify default realm"
By the way, I can not find anywhere the GSI mechanism OID..

**Comment by simo5** [comment]
> The `client_ctx.step()` return an error sayng: "Configuration file does not specify default realm"
This means you are still hitting the kerberos mechanism.

> By the way, I can not find anywhere the GSI mechanism OID..

Ok, where have you got the GSI mechanism package from ? There surely
must be some documentation in it or example file to make it loaded by
the gssapi mechglue.

**Comment by muccix** [comment]
The C++ client I'm trying to replicate seems to use "GSS_C_NO_NAME" as target_name.

I see a commen this comment [here](https://github.com/pythongssapi/python-gssapi/blob/12aa6af1b79fe5ee32f510760ac2a9bdb76f80cf/gssapi/raw/sec_contexts.pyx#L111):

# TODO(directxman12): figure out whether GSS_C_NO_NAME can be passed in here

Is it possible that "GSS_C_NO_NAME" is not managed at the moment?

**Comment by simo5** [comment]
@muccix you are barking up the wrong tree.
First figure out how to load GSI, then you can infer anything about the names it my or not like

**Comment by pdonorio** [comment]
Hi all, I'm working with @muccix in this issue. It seems that so far we didn't really understand very clearly how to proceed, so let me try a brief summary of what we are doing, maybe someone of you can help us get unstuck with more information.

We are try to port the C `libgsi` authentication plugin for an iRODS server into a Python library.

In our python version we are already connected to the iRODS server and able to send messages to authenticate. 

The C working block that allows this authentication via iRODS message in our case is [here](https://github.com/irods/irods_auth_plugin_gsi/blob/master/gsi/libgsi.cpp#L529-582).

In particular there is a call to `gss_init_sec_context` right there, and that's the point to solve, which seems to follow the pattern of your basic tutorial for [security context](https://pythonhosted.org/gssapi/basic-tutorial.html?highlight=oid#security-contexts). 

Following the tutorial the default mechanism used is kerberos. After making some tests If we create a new context changing the `target_name` there it seems to finally switch from kerberos to another mechanism. What is the right one to use? Again please see in our C related code the OID used is `GSS_C_NO_NAME` (which basically means NULL or Zero).

Going deeper into this repo code it looks like there is no way to generate an OID from that specific code, maybe it's not yet supported or the case wasn't ever tested.

One thing to note is that our iRODS server can correctly receive a GSS authentication request message so far, but it's not understanding the protocol because the context is not the right one.

Thanks a lot for helping.

**Comment by simo5** [comment]
I think the reason it works in your C++ application is in ... the Makefile.
Basically you are linking directly to an alternative GSSAPI implementation, instead of linking to the standard GSSAPI and loading the Globus mechanism using the standard mechglue interfaces to do that.

The confusion arise from the fact that unfortunately in GSSAPI the GSS API and the plugins SPI use the same symbol names so it is something unclear whether you are using the system GSSAPI or directly linking to a mechianism.

However the differences are evident at execution time. Specifically if you link directly to the mechanism code an OID is not necessary because there is no mechanism, to select as you are calling directly into the mechanism by linking into it. When you use an actual GSSAPI library with a mechglue instead you have to use an OID to identify the mechanis.
Now that OID does not have to be specified by the mechanism code, it is instead specified in the mechglue configuration that loads the mechanis shared object.

For example this is how the NTLMSS GSSAPI mechanism condifugration file for GSSAPI looks like:
https://github.com/simo5/gss-ntlmssp/blob/master/examples/mech.ntlmssp.in

Searching for the Globus GSI OID ends up finding this code:
https://github.com/jglobus/JGlobus/blob/master/gss/src/main/java/org/globus/gsi/gssapi/GSSConstants.java which declares 1.3.6.1.4.1.3536.1.1 as the GSI OID (3536 is the Globus identifier as per IANA registry and seem the same OID is found also in some openssh patches to enable use of the GSI mechanism).

So I would guess what youneed is to load the globus GSI shared object in GSSAPI by using a /etc/gss/mech.d/gsi.conf  file with gsi as the name, the OID above as oid and the patch to the globus .so file.

Once you do that, you will be able to sue the GSI mechanism (to the exclusion of any other mechanism) by specifying the above OID in your code, alternatively if you want to support multiple mechanisms you can still pass the NULL OID, this will initialize credentials for all the mechanism that recognize the name and have matching creds and defer to the context establishment code to select an appropriate mechanism.

HTH.
Simo.

**Comment by muccix** [comment]
@simo5 thanks lot, this clarifies a lot of things!

Following you suggestion, I have created the /etc/gss/mech.d/gsi.conf file containing:

`gsi                     1.3.6.1.4.1.3536.1.1.1            /usr/lib/x86_64-linux-gnu/libglobus_gssapi_gsi.so`

(also tried with 1.3.6.1.4.1.3536.1.1, see [here](https://github.com/globus/globus-toolkit/blob/globus_6_branch/gsi/gssapi/source/library/oid_functions.c))

And then set the server name as:

`server_name = gssapi.Name('0', name_type=gssapi.OID.from_int_seq('1.3.6.1.4.1.3536.1.1.1'))`

But I get:

File "gssapi/raw/sec_contexts.pyx", line 244, in gssapi.raw.sec_contexts.init_sec_context (gssapi/raw/sec_contexts.c:2290)
gssapi.raw.exceptions.BadNameTypeError: Major (196608): A supplied name was of an unsupported type, Minor (100001): Success

Any suggestions?
Thanks again

**Comment by simo5** [comment]
Name types != Mech types.

Import the name normally, the OID needs to be used with the context functions.

**Comment by pdonorio** [comment]
Very good simo, we finally started to see something working.

This block of code can show where we arrived so far: [link](https://github.com/EUDAT-B2STAGE/python-irodsclient/blob/744fe494cfacd040e0b26b57839bc4f7ed3baeb4/irods/connection.py#L108-L140)

Client is created correctly only if you pass with shell variables the X509 certificates files.

Server maybe should be created from a Server DN string as we saw in the C++ version of the GSI plugin.
We also should probably use host/port but I can't understand how.

We fail once we pass the initial client token to the server, like this:

The execution logs is:
```bash
# python testgsi.py
('CLIENT', 'FgMBAUQBAAFAAwNvQIVeD9zUoYIdGjuJV48/u32AsLLyToNOf++769rB1wAAwsAQwAbAFcALwAEAOwACAAHAMMAswCjAJMAUwAoApQCjAKEAnwBrAGoAaQBoADkAOAA3ADYAiACHAIYAhcAZwDLALsAqwCbAD8AFAJ0APQA1AITAL8ArwCfAI8ATwAkApACiAKAAngBnAEAAPwA+ADMAMgAxADAAmgCZAJgAlwBFAEQAQwBCwBjAMcAtwCnAJcAOwAQAnAA8AC8AlgBBwBHAB8AWwAzAAgAFAATAEsAIABYAEwAQAA3AF8ANwAMACgD/AQAAVQALAAQDAAECAAoAHAAaABcAGQAcABsAGAAaABYADgANAAsADAAJAAoAIwAAAA0AIAAeBgEGAgYDBQEFAgUDBAEEAgQDAwEDAgMDAgECAgIDAA8AAQE=', False)
instance(SecurityContext):
  _INQUIRE_ARGS: ('initiator_name', 'target_name', 'lifetime', 'mech', 'flags', 'locally_init', 'complete'),
  _channel_bindings: None,
  _complete: None,
  _creds: <gssapi.creds.Credentials object at 0x7feb0a7a6e50>,
  _last_err: None,
  _started: False,
  complete: False,
  delegated_creds: None,
  usage: 'accept'
Traceback (most recent call last):
  File "testgsi.py", line 37, in <module>
    coll = sess.collections.get("/tempZone/home/rods")
  File "/code/irods/manager/collection_manager.py", line 15, in get
    result = query.one()
  File "/code/irods/query.py", line 217, in one
    results = self.execute()
  File "/code/irods/query.py", line 169, in execute
    with self.sess.pool.get_connection() as conn:
  File "/code/irods/pool.py", line 22, in get_connection
    conn = Connection(self, self.account)
  File "/code/irods/connection.py", line 35, in __init__
    self._login()
  File "/code/irods/connection.py", line 150, in _login
    token = self.getAuthToken('rodserver')
  File "/code/irods/connection.py", line 139, in getAuthToken
    initial_server_token = server_ctx.step(initial_client_token)
  File "<decorator-gen-9>", line 2, in step
  File "/usr/lib/python2.7/dist-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib/python2.7/dist-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gssapi/sec_contexts.py", line 506, in step
    return self._acceptor_step(token=token)
  File "/usr/lib/python2.7/dist-packages/gssapi/sec_contexts.py", line 512, in _acceptor_step
    self, self._channel_bindings)
  File "gssapi/raw/sec_contexts.pyx", line 368, in gssapi.raw.sec_contexts.accept_sec_context (gssapi/raw/sec_contexts.c:3119)
gssapi.raw.exceptions.InvalidTokenError: Major (589824): Invalid token was supplied, Minor (0): Unknown error
```

Do we have a way to debug more?

**Comment by simo5** [comment]
The errors come directly from the mechanism's gss_accept_sec_context function, python-gssapi has no more info than this, next stp is checking in what cases that major error is returned (note it is not a valid GSSAPI Major error, so already suspicious, and gdb otherwise.

**Comment by pdonorio** [comment]
Absolutely, it's a problem with how to deal the handshake in respect to the server. We'll continue digging on the other issue inside the irods repo and update here when we find a solution or a problem related to the GSS api calls.

**Comment by pdonorio** [comment]
Ok, [here's our working handshake](https://github.com/EUDAT-B2STAGE/python-irodsclient/blob/b5431dc10d907e302659d49b760c3014230b7f2b/irods/connection.py#L171-L189) with the GSS API towards our iRODS server through the GSI plugin.

Two notes:

1. We had to learn how to write messages to iRODS to exchange tokens. That part didn't belong to this issue.
2. To provide a valid client context with GSI mechanism, this is the peace of code that work:
```python
import gssapi

GSI_OID = "1.3.6.1.4.1.3536.1.1" 

gsi_mech = gssapi.raw.OID.from_int_seq(GSI_OID)

server_name = gssapi.Name(SERVER_DN)
server_name.canonicalize(gsi_mech)

client_ctx = gssapi.SecurityContext(name=server_name, mech=gsi_mech, usage='initiate')

```

where `SERVER_DN` is the DN of the server X509 certificate.
You may start it with
```python
SERVER_DN = "/CN=test"
```
and the client should tell you which server_dn is expected.

The GSI mechanism should be configured on the client host, for example like so:
```bash
$ more /etc/gss/mech.d/gsi.conf

# GSI mechanism plugin
#
# copy this file in /etc/gss/mech.d
#
# Mechanism Name    Object Identifier       Shared Library Path         Other Options
gsi_v1          1.3.6.1.4.1.3536.1.1		/usr/lib/x86_64-linux-gnu/libglobus_gssapi_gsi.so
```

Thanks so much for helping, hope our code will help others too.

You may close the issue ;)

**Comment by muccix** [comment]
I confirm it works, thanks a lot!

**Comment by simo5** [comment]
@muccix or @pdonorio may you be able to write your last comment in form of an Howto docuemnt so we add it as an example to the documentation ?

**Comment by muccix** [comment]
Here is a summary of the steps needed to create a python client which uses GSI authentication (in this case against an iRODS with GSI authentication enabled)

First of all you need to create a file which  maps the GSI OID to the Globus GSSAPI library:
   

    $ more  /etc/gss/mech.d/gsi.conf
    # GSI mechanism plugin
    #
    # Mechanism Name        Object Identifier               Shared Library Path                   
    gsi                     1.3.6.1.4.1.3536.1.1.1          /usr/lib/x86_64-linux-gnu/libglobus_gssapi_gsi.so


Then in the client:
1.  Set the  authorization mechanism:
```
gsi_mech = gssapi.raw.OID.from_int_seq('1.3.6.1.4.1.3536.1.1.1')
```

2. Set the server name using the server X.509 DN:
```
server_name = gssapi.Name(<serverDN>)
server_name.canonicalize(gsi_mech)
```

3. Create the client context:
```
self.client_ctx = gssapi.SecurityContext(
                name=server_name,
                mech=gsi_mech,
                flags=[2, 4],
                usage='initiate')
```

4. Start the token exchange loop in _def handshake(self, target)_:
```
def send_gsi_token(self, server_token=None):

    # CLIENT TOKEN
    if server_token is None:
        client_token = self.client_ctx.step()
    else:
        client_token = self.client_ctx.step(server_token)
    logger.debug("[GSI handshake] Client: sent a new token")

    # SEND IT TO SERVER
    self.reply(len(client_token))
    self.socket.sendall(client_token)

def receive_gsi_token(self):

    # Receive client token from iRODS
    data = self.socket.recv(4)
    value = struct.unpack("I", bytearray(data))
    token_len = socket.ntohl(value[0])
    server_token = self.recvall(token_len)
    logger.debug("[GSI handshake] Server: received a new token")

    return server_token

def handshake(self, target):
    """
    This GSS API context based on GSI was obtained combining 2 sources:
https://pythonhosted.org/gssapi/basic-tutorial.html
https://github.com/irods/irods_auth_plugin_gsi/blob/master/gsi/libgsi.cpp
    """

    self.init_sec_context()

    # Go, into the loop
    self.send_gsi_token()

    while not (self.client_ctx.complete):

        server_token = self.receive_gsi_token()

        self.send_gsi_token(server_token)

    logger.debug("[GSI Handshake] completed")
```

The full code is available in the [python-irodsclient](https://github.com/irods/python-irodsclient) library.

**Comment by DirectXMan12** [comment]
@muccix do you mind if we adapt what you wrote above into an example/tutorial of how to use Python-GSSAPI with a non-KRB5 mechanism in our documentation (with attribution, of course 😃 )?

**Comment by muccix** [comment]
No worries, go on!

**Comment by DirectXMan12** [comment]
Thanks!
