### ISSUE TITLE
Assertion's dependencies in tests

### ISSUE THREAD

**Issue by stanislavlevin** [pythongssapi/python-gssapi#130]
Hello.

python-gssapi tests are using shouldbe python module(based on forbiddenfruit), which are look like abandoned and are not supported python 3.5 and above. Moreover, most of Linux distr are not packing these modules, so there is no possibility to run tests of python-gssapi during build time.

I've prepared a patch to change assertion code to nose(based on unittest).
An attached patch is for v1.2.2 + fix [https://github.com/pythongssapi/python-gssapi/commit/bd6184406bfd754dff0594a840c3338ae3572fca](https://github.com/pythongssapi/python-gssapi/commit/bd6184406bfd754dff0594a840c3338ae3572fca)
All tests have been passed.

Thank you.

[0001-Change-assertion-s-Python-dependencies-from-shouldbe.patch.txt](https://github.com/pythongssapi/python-gssapi/files/1492465/0001-Change-assertion-s-Python-dependencies-from-shouldbe.patch.txt)

21/11/2017: patch was updated due to i586 build error(fixed)

**Comment by frozencemetery** [comment]
@DirectXMan12 can you confirm or deny that you abandoned your own python module? :P 

More seriously though, as the guy who does the packaging for three of them, being able to run tests at build time in distros would be nice.

**Comment by stanislavlevin** [comment]
My Linux distro is AltLinux(rpm-based).
I guess tests are very important and unfortunately there was no tests running before.

**Comment by DirectXMan12** [comment]
> @DirectXMan12 can you confirm or deny that you abandoned your own python module? :P

I can neither confirm nor deny that.  Please see [redacted] for [redacted] [redacted] :-P

On a more serious note, I've just tested locally on Python 3.5, and `should_be` works fine in Python 3.5.  That being said, I wouldn't mind an extension to `should_be` or something of the sort to allow the use of an `expect(xyz).to_be(abc)` instead of using forbiddenfruit.  It shouldn't be too hard.  I don't have a lot of time right now, but I'd certainly accept a patch.

In any case, we accept patches in the form of GitHub pull requests, so please submit any future changes in that form.
