### ISSUE TITLE
generate client token problem

### ISSUE THREAD

**Issue by belyaev-pa** [pythongssapi/python-gssapi#165]
### What went wrong?
Hi. I am having a problem with export client token. I am not very experienced with Kerberos so I might be doing something wrong. 

### How do we reproduce?

I tried to generate negotiate token on the client side:
```
        user = 'ksa1c1g1u1'
        os.environ['KRB5_KTNAME'] = 'FILE:/etc/krb5.keytab'
        user_name = gssapi.Name(user, name_type=gssapi.NameType.kerberos_principal)
        user_creds = gssapi.Credentials(usage='initiate', name=user_name)        
        token = base64.b64encode(user_creds.export())
```
and then send it to server side for authorization:
```
def authz_handler(client_token):
    os.environ['KRB5_KTNAME'] = 'FILE:/etc/httpd/http.keytab'
    os.environ['KRB5_CONFIG'] = '/etc/krb5.conf'
    service = 'HTTP@authzserv.che.com'
    server_name = gssapi.Name(service, name_type=gssapi.NameType.hostbased_service)
    server_creds = gssapi.Credentials(usage='accept', name=server_name)
    ctx = gssapi.SecurityContext(creds=server_creds, usage='accept')
    _unused_server_tok = ctx.step(base64.b64decode(client_token))
    user_name = ctx.initiator_name
    principal = user_name.display_as(user_name.name_type)
    return principal
```
when i run it i get token error

```
File "/opt/auth/authz.py", line 24, in authz_handler
    _unused_server_tok = ctx.step(base64.b64decode(client_token))
  File "<decorator-gen-9>", line 2, in step
  File "/usr/lib64/python2.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib64/python2.7/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/gssapi/sec_contexts.py", line 519, in step
    return self._acceptor_step(token=token)
  File "/usr/lib64/python2.7/site-packages/gssapi/sec_contexts.py", line 525, in _acceptor_step
    self, self._channel_bindings)
  File "gssapi/raw/sec_contexts.pyx", line 368, in gssapi.raw.sec_contexts.accept_sec_context
InvalidTokenError: Major (589824): Invalid token was supplied, Minor (0): Unknown error
```

Verification with Negotiate token created by Mozilla Firefox works well. I think I am using the wrong way to generate the token.
Any help would be appreciated.

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
RHEL7
python-gssapi-1.2.0-2.el7.x86_64
FreeIPA

**Comment by simo5** [comment]
Thi usage is incorrect, you are trying to export the user's credentials instead of obtaining a GSSAPI Security context initiator token.

The process to establish a security context is mostly symmetrical between clioent and server.
You need to call ctx = gssapi.SecurityContext(server=server_name, usage='initiate') on the client, then ctx.step() and send the resulting token to the server, keep looping on step until while continuation needed status is true and stop only if a complete status is return or an error happens.

Read the tutorial here for more info and the docs around security contexts:
https://pythongssapi.github.io/python-gssapi/latest/basic-tutorial.html#security-contexts

Not a bug.
