### ISSUE TITLE
gssapi pip installation failed

### ISSUE THREAD

**Issue by subash2517** [pythongssapi/python-gssapi#171]
### What went wrong?

 Failed building wheel for gssapi

Command "/opt/local/bgdatapp/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lz9pf3jh/gssapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8zm5qiux/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-lz9pf3jh/gssapi/

### How do we reproduce?
 ./pip install gssapi
*(Remember to use fenced code blocks and consider placing in a gist if large)*

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
gssapi
*(Please include MIT/Heimdal/etc. and how you installed python-gssapi)*

**Comment by frozencemetery** [comment]
Hi, I need you to actually fill out the component versions section, not just write "gssapi".

**Comment by subash2517** [comment]
I am tried last 3 version non of them created wheel. 

Python version 3.7.2
Gssapi 1.5

**Comment by frozencemetery** [comment]
As the item asks, please provide Kerberos version and vendor, OS version, and distro version.

**Comment by subash2517** [comment]
Kerberos 5 release 1.10.3
Linux 2.6.32-754.6.3.el6.x86_64

**Comment by frozencemetery** [comment]
Is there a reason you're not telling me OS/distro version?  It makes it very hard to help you when you don't answer my questions.

Based on the package name, that looks like CentOS 6.  Support for that is best-effort: the python, setuptools, and cython shipped with CentOS 6 are all too old to work with python-gssapi.  In order to run python-gssapi here, you need to use the python-3.6 from epel6 in a virtualenv.  Testing locally, this all works:

```
virtualenv -p python3 .venv
source .venv/bin/activate
pip install gssapi
python -c 'import gssapi; exit(0)'
```

The python executable you're running appears to come from an anaconda installation.  Neither us nor the anaconda team supports using that python for this purpose.

**Comment by subash2517** [comment]
Our OS is Red Hat Enterprise Linux Server release 6.10 (Santiago) .  The above solution is not working.

**Comment by frozencemetery** [comment]
If you're not going to actually follow the solution I gave you, of course it won't work.  See previous comment.
