### ISSUE TITLE
gssapi issue

### ISSUE THREAD

**Issue by subash2517** [pythongssapi/python-gssapi#172]
### What went wrong?

Command "/opt/local/bgdatapp/anaconda3/bin/python -u -c "import setuptools, toke                                                                  nize;__file__='/tmp/pip-install-40mup4_y/gssapi/setup.py';f=getattr(tokenize, 'o                                                                  pen', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile                                                                  (code, __file__, 'exec'))" install --record /tmp/pip-record-9xzmwwrh/install-rec                                                                  ord.txt --single-version-externally-managed --compile" failed with error code 1                                                                   in /tmp/pip-install-40mup4_y/gssapi/

### How do we reproduce?
./pip install gssapi
*(Remember to use fenced code blocks and consider placing in a gist if large)*

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
gssapi 1.5.1
Red Hat Enterprise Linux Server release 6.10 (Santiago) 
Kerberos 5.

*(Please include MIT/Heimdal/etc. and how you installed python-gssapi)*
It is anaconda3 version.
./pip install gssapi

**Comment by frozencemetery** [comment]
As I told you in #171: "The python executable you're running appears to come from an anaconda installation. Neither us nor the anaconda team supports using that python for this purpose."

As I further stated there: " In order to run python-gssapi here, you need to use the python-3.6 from epel6 in a virtualenv."

I'm going to close your tickets until you do that because you don't have actual issues, just unsupported configurations.
