### ISSUE TITLE
Why do we upload a different tarball to GitHub than to PyPI

### ISSUE THREAD

**Issue by atodorov** [pythongssapi/python-gssapi#206]
This is what the GitHub action does:

```
                    "name": "Upload release tarball",
                    "uses": "actions/upload-release-asset@v1",
                    "env": { "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}" },
                    "with": {
                        "upload_url": "${{ steps.cr.outputs.upload_url }}",
                        "asset_path": "tag_build/*.tar.gz",
                    },
```

There is corresponding code in `before-deploy.sh` which creates the tarball. 

@frozencemetery  is there any particular reason why doesn't this action upload the tarball found in `dist/` which has been built by `python setup.py sdist` at the beginning of `before-deploy` ?

**Comment by frozencemetery** [comment]
The github tarball is source, while the pypi one is... well, whatever pypi wanted :)

The PyPI tarball has been cythonized, while the GitHub one hasn't.  (If you look at the file listings, the pypi one has largely .c and .pxd files in raw, while the github one has .pyx and .pxd files.)  So, since the C files are generated code, the pypi tarball isn't sufficient to count as distributing the full source - which is what we need to do (e.g., for distros).

Does that make sense?

**Comment by atodorov** [comment]
> Does that make sense?

Yes, now it does.
