### ISSUE TITLE
Centos6 'module' object has no attribute 'C_NT_HOSTBASED_SERVICE'

### ISSUE THREAD

**Issue by robgil** [pythongssapi/python-gssapi#90]
The demo is failing on the constant gssapi.C_NT_HOSTBASED_SERVICE in CentOS 6.
* krb5-libs-1.10.3-37.el6_6.x86_64
* Python 2.6.6

```python
import gssapi

# Create a Name identifying the target service
service_name = gssapi.Name('HTTP@<myserver>', gssapi.C_NT_HOSTBASED_SERVICE)
# Create an InitContext targeting the demo service
ctx = gssapi.InitContext(service_name)

# Loop sending tokens to, and receiving tokens from, the server
# until the context is established
in_token = None
while not ctx.established:
    out_token = ctx.step(in_token)
    if out_token:
        send_to_server(out_token)
    if ctx.established:
        break
    in_token = receive_from_server()
    if not in_token:
        raise Exception("No response from server.")

print("Successfully authenticated.")

```
Output
```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    service_name = gssapi.Name('HTTP@ipa001.dev.ikanow.com', gssapi.C_NT_HOSTBASED_SERVICE)
AttributeError: 'module' object has no attribute 'C_NT_HOSTBASED_SERVICE'
```

**Comment by frozencemetery** [comment]
This applies to all versions of all systems because this is unfortunately not from our docs.  Our docs are at https://pythonhosted.org/gssapi/ ; unfortunately, you have stumbled across a version of an earlier project that somehow slipped by without being marked depricated.

If you would like similar example code, [our SecurityContext](https://pythonhosted.org/gssapi/gssapi.html#gssapi.sec_contexts.SecurityContext.step) docs or [this thing that will be integrated into the main repository hopefully soon](https://gist.github.com/DirectXMan12/7d8a7049420979589332) might help.

Apologies for the confusion!
